BEGIN TRANSACTION;

CREATE TABLE users(
	id INTEGER PRIMARY KEY,
	username TEXT UNIQUE,
	pwhash TEXT,
	secret TEXT
);

CREATE TABLE messages(
	id INTEGER PRIMARY KEY,
	user_id INTEGER REFERENCES users,
	message TEXT
);

COMMIT;